### PR TITLE
Made date field readonly

### PR DESCRIPTION
**Pull request by schtibe**
Made the date field in the post contribution form readonly. Otherwise it
is possible to mess with the date and easily get NaN-NaN-NaN sort of
stuff

### CODE REVIEW

**Comment by Joshuasony** [comment]
thx, schtibe!

**Comment by topaxi** [comment]
The Datefield was writable as people might post contributions from yesterday. This should be catched by validations, not by disabling it.

**Comment by topaxi** [comment]
Basically, if validations aren't working, somethings wrong here:
https://github.com/opensource-challenge/opensource-challenge-client/blob/master/app/validations/contribution.js
or we should check for validity here:
https://github.com/opensource-challenge/opensource-challenge-client/blob/master/app/post-contribution/route.js#L31

**Comment by schtibe** [comment]
Alright! The thing is, as soon as you hit backspace to change the date, you get NaN-aN-aN. Maybe use a date picker?

**Comment by topaxi** [comment]
I see! I'm using FF nightly and Chrome, these have Datepickers 😆 

Datepicker would be nice. http://www.ember-power-calendar.com/ is a nice candidate here.

**Pull request merged**
